### ISSUE TITLE
Failure to assign materials to noncontiguous volumes

### ISSUE THREAD

**Issue by elliottbiondo** [svalinn/mcnp2cad#14]
MCNP5 allows for the creation of volumes that are disparate in space. MCNP2CAD properly creates these volumes, but fails to assign them to the corresponding material group. Consider the following minimum working example. This input should yield a single MCNP volume made up of 2 slices of a cylinder:
```
TITLE CARD
c cell cards
1 1 1.0  (-1 2):(-1 -3)
2 0 1:(-1 -2 3)

c surface cards
1 c/x 0 0 2
2 py 1
3 py -1
```
CUBIT creates 2 volumes (as expected) but material group 1 is empty:
![mcnp2cad_bug](https://cloud.githubusercontent.com/assets/1749283/5888410/4057906c-a3c3-11e4-99c3-3070cf0ecbd3.png)

**Comment by sjackso** [comment]
Hi @elliottbiondo!

Huh, I thought we had fixed this, but it's getting to be a pretty long time since I worked on this, so memory may well be fallable.  :)

Although there are two volumes, there should only be one "body," which ought to be correctly assigned to the material group.  Cell numbers should also be correctly applied to this body.  (Is this Cubit you're using to read the output?  Have you right-clicked and refreshed the part tree?  I don't remember whether bodies appear as you would expect in the Cubit listing; it's possible that all is well, but that Cubit isn't showing you what you want.)  The body/volume distinction exists exactly for this situation.

**Comment by elliottbiondo** [comment]
Hi @sjackso! Upon further inspection I believe you are correct -- this is just an issue of CUBIT only displaying volumes within a group, not bodies.

CUBIT shows that material group 1 is empty:
```
CUBIT> list Group 2
Group Entity 'mat_1_rho_1' (Id = 2)
It owns/encloses 0 entities.
	Owned Entities: None.
```
However, ```lcad``` file produced by MCNP5 shows the correct material assignments:

```
1  0 imp:n=0
2 1 1 imp:n=1
3 1 1 imp:n=1
4 0 imp:n=1
5 0 imp:n=1 $ implicit complement
```

so I think there is no cause for alarm here. Thanks for the insight! Closed.
