### ISSUE TITLE
Explore matrix capability of CGM

### ISSUE THREAD

**Issue by gonuke** [svalinn/mcnp2cad#28]
It may be possible to replace Armadillo with methods in `AnalyticGeometryTool.[ch]pp` and `CubitMatrix.[ch]pp`

**Comment by Pshriwise** [comment]
After looking through those files, I don't see the capability to calculate the pseudo-inverse directly or via SVD :(

**Comment by gonuke** [comment]
`CubitMatrix` has an inverse() method for 3x3 matrices - isn't that all you need?

**Comment by Pshriwise** [comment]
I specifically need the pseudo-inverse (aka Moore-Penrose inverse) to find the inverse that has a minimal translation magnitude (which manifests as an inverse with the solution to a linear least squares problem) for the GQ in order to get the translation correct for GQs with an infinite dimension (e.g. elliptical cylinders).

This could also be accomplished by using the singular value decomposition and then some matrix multiplication, but I don't see that in there either.

**Comment by gonuke** [comment]
OK - got it...

**Comment by gonuke** [comment]
BTW, I think Armadillo's license (Mozilla) will allow us to vendor it into the plugin code base.  It's CMake build system should further support that.
